sudo: required

language: ruby

rvm:
  # Rails 5 requires 2.2
  - 2.3.1
  - 2.4.1
  - 2.5.0
  - 2.2.6
services:
  - docker

cache:
  bundler: true
  directories:
    - node_modules # NPM packages
  yarn: true

gemfile:
  - spec/dummy/Gemfile
  - spec/dummy_no_webpacker/Gemfile.rails32

env:
  global:
    - RAILS_ENV=test
    - DRIVER=selenium_chrome
    - CHROME_BIN=/usr/bin/google-chrome
    - USE_COVERALLS=TRUE

before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen scn 1600x1200x16"

install:
  - travis_retry gem install bundler
  - travis_retry nvm install 8.11.3
  - node -v
  - travis_retry npm i -g yarn
  - travis_retry bundle install
  - travis_retry yarn
  - travis_retry yarn run build
  - bundle exec rake prepare_for_ci

before_script:
  - "export DISPLAY=:99"

script:
  - bundle exec rake

matrix:
  exclude:
    - gemfile: spec/dummy_no_webpacker/Gemfile.rails32
      rvm: 2.3.1
    - gemfile: spec/dummy_no_webpacker/Gemfile.rails32
      rvm: 2.4.1
    - gemfile: spec/dummy_no_webpacker/Gemfile.rails32
      rvm: 2.5.0
    - gemfile: spec/dummy/Gemfile
      rvm: 2.2.6
